apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rx1412d6z-nodejs-gitops
  description: This is GitOps manifest for rx1412d6z-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rx1412d6z-nodejs
    backstage.io/kubernetes-id: rx1412d6z-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rx1412d6z-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rx1412d6z-nodejs
